CREATE TABLE books (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(100) NOT NULL,
    author VARCHAR (60) NOT NULL,
    isbn VARCHAR(30) UNIQUE NOT NULL,
    available BOOLEAN NOT NULL DEFAULT TRUE
);