CREATE TABLE loans (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    book_id BIGINT NOT NULL,
    reader_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL
);

ALTER TABLE loans ADD CONSTRAINT FK_LOANS_BOOKS
FOREIGN KEY (book_id) REFERENCES books(id);

ALTER TABLE loans ADD CONSTRAINT FK_LOANS_READERS
FOREIGN KEY (reader_id) REFERENCES readers(id);
